name = "qurl-api"
# Set CLOUDFLARE_ACCOUNT_ID env var instead of hardcoding
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "URL_CACHE"
id = "156b39cc51ad4e86b92d3f62d36a9f32"

[env.dev]
[env.dev.vars]
ENVIRONMENT = "development"

[[env.dev.kv_namespaces]]
binding = "URL_CACHE"
id = "26c7665d606343b3a3f6bf8d8869fa95"

[[routes]]
pattern = "api.qurl.nazarf.dev"
custom_domain = true
